#!/bin/sh
#
# busybox init script for loading centrifuge dependencies 
#

case "$1" in
  start)
    echo "Setting up centrifuge"
	insmod /usr/share/centrifuge_mmap.ko
    ;;
  stop)
    echo -n "There is nothing to stop for centrifuge"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
